### PR TITLE
warn when unable to locate a package repository URL

### LINKED ISSUE #508: rsconnect cannot deploy applications using packages currently archived on CRAN
For example, the [Kmisc](https://cran.r-project.org/web/packages/Kmisc/index.html) package has been archived on CRAN, but users can still install and use old versions of the package. Attempting to deploy such a package will fail:

```
----- Bundle upload started at  2021-05-03 16:01:06  -----
[2021-05-03 16:01:06] Inferring App mode and parameters 
[2021-05-03 16:01:06] Bundling app dir 
[2021-05-03 16:01:06] Generate manifest.json 
Warning: Unable to determine the repository for package Kmisc
----- Deployment error -----
Error: 
* Unable to determine the location for some packages. Packages must
   come from a package repository like CRAN or a source control system.
   Check that options('repos') refers to a package repository
   containing the needed package versions.
 
----- Error stack trace -----
Error: 
* Unable to determine the location for some packages. Packages must
   come from a package repository like CRAN or a source control system.
   Check that options('repos') refers to a package repository
   containing the needed package versions.
Error during wrapup: length(max.lines) <= 1 is not TRUE
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Execution halted
```

even though technically that package is still available and can be restored.

### PR DESCRIPTION
**Pull request by aronatkins**
Previously, we would err (and prohibit manifest creation and/or deployment)
when unable to locate a repository URL for a named package. Now, warn and
allow the operation to proceed.

Archived CRAN packages are not discoverable through available.packages.

Source-installed packages do not have repository URLs, but may have been
installed locally on the server (and configured as an external package
dependency).

This consolidates three separate checks against the package repository and source.

Fixes #508

Given a Shiny application with:

```r
# remotes::install_version("Kmisc", "0.5.0")
library(Kmisc)

# A locally-created, installed-from-source package.
library(silly)
```

Calling `rsconnect::writeManifest()` produces:

```
Warning: 
* May be unable to deploy package dependency 'Kmisc'; could not
   determine a repository URL for the source 'CRAN'.

* May be unable to deploy package dependency 'silly'; could not
   determine a repository URL for the source 'CRAN'.

* Unable to determine the source location for some packages. Packages
   should be installed from a package repository like CRAN or a
   version control system. Check that options('repos') refers to a
   package repository containing the needed package versions.
Warning message:
In FUN(X[[i]], ...) :
  Package 'silly 0.1.0' was installed from sources; Packrat will assume this package is available from a CRAN-like repository during future restores
```

That final message is triggered by `packrat` but not displayed immediately, so it shows up last.

### CODE REVIEW

File: R/bundle.R [hunk 1]
```diff
@@ -833,17 +832,16 @@ createAppManifest <- function(appDir, appMode, contentCategory, hasParameters,
 }
 
 validatePackageSource <- function(pkg) {
-  msg <- NULL
```
Comment (aronatkins) [inline R/bundle.R:836]: The old version of `validatePackageSource` was effectively a no-op, since the repository had an `NA` value rather than `NULL`, as identified during https://github.com/rstudio/rsconnect/pull/493.

**Comment by aronatkins** [comment]
This work is also connected to situations like those reported in #505.

File: R/bundle.R [hunk 2]
```diff
@@ -729,30 +721,37 @@ createAppManifest <- function(appDir, appMode, contentCategory, hasParameters,
...
+    #   * CRAN-archived packages are not visible to our available.packages scanning.
+    #   * Source-installed packages may be available after a manual server-side installation.
     #
-    # It's possible we cannot find a repository URL for other reasons, including when folks locally
-    # build and install packages from source. An incorrectly configured "repos" option is almost
-    # always the cause.
-    msg <- c(msg, sprintf("Unable to determine the location for some packages. Packages must come from a package repository like CRAN or a source control system. Check that options('repos') refers to a package repository containing the needed package versions."))
+    # That said, an incorrectly configured "repos" option is almost always the cause.
+    packageMessages <- c(packageMessages,
+                         "Unable to determine the location for some packages. Packages should be installed from a package repository like CRAN or a source control system. Check that options('repos') refers to a package repository containing the needed package versions.")
```
Comment (kevinushey) [inline R/bundle.R:748]:
```suggestion
                         "Unable to determine the source location for some packages. Packages should be installed from a package repository like CRAN or a version control system. Check that options('repos') refers to a package repository containing the needed package versions.")
```

File: R/bundle.R [hunk 3]
```diff
@@ -729,30 +721,37 @@ createAppManifest <- function(appDir, appMode, contentCategory, hasParameters,
...
+    warning(paste(formatUL(packageMessages, '\n*'), collapse = '\n'), call. = FALSE, immediate. = TRUE)
```
Comment (kevinushey) [inline R/bundle.R:749]: One potential nit: in some cases, users might turn warnings into errors via `options(warn = 2)` or similar. We could use `message()` instead to write the message without worry that R might be configured to treat warnings as fatal. Is that worth changing?

```suggestion
    message(paste(formatUL(packageMessages, '\n*'), collapse = '\n'))
```

(we might already be warning in other contexts though)

**Review by kevinushey — COMMENTED** [review]
LGTM; main comment is around whether we might want to use `message()` instead of `warning()`. (`warning()` is probably fine, but worth double-checking)

**Review by jmcphers — APPROVED** [review]
LGTM pending Kevin's remarks. Has this been tested by anyone other than yourself? It's a big enough change that we might want to do some sanity checks before sending it to CRAN.

File: R/bundle.R (hunk 3 above)
Comment (aronatkins) [reply R/bundle.R:749]: I'm OK with either option (warning or message). If folks change warnings into errors, that gives the option of hard-feedback that this PR is removing. That feels like a positive, no?

I don't feel strongly about this.

**Comment by aronatkins** [comment]
@jmcphers - testing only by myself right now. I'm about to solicit others. The good news is that we're converting errors to warnings, so the primary danger should be an occasional false warning. To be honest, the warning about `Kmisc` saddens me, but there's not a lot to be done, from what I understand.

**Review by kevinushey — APPROVED** [review]
LGTM!

**Comment by jmcphers** [comment]
@aronatkins thanks, just merged! I'm planning on performing the CRAN submission on Monday, 5/24.
