### PR TITLE
fix: skip signature testing on CRAN

### LINKED ISSUE #1255: CRAN: r-devel errors
<https://cran.r-project.org/web/checks/check_results_rsconnect.html>

```
    • On Linux (3): 'test-locale.R:2:3', 'test-locale.R:9:3', 'test-utils.R:112:3'
    
    ══ Failed tests ════════════════════════════════════════════════════════════════
    ── Error ('test-http.R:74:5'): authHeaders() picks correct method based on supplied fields ──
    Error in `hash_sign(md, sk)`: OpenSSL error: C0E88FFCFB7E0000:error:03000098:digital envelope routines:evp_pkey_ctx_set_md:invalid digest:crypto/evp/pmeth_lib.c:966:
    
    Backtrace:
        ▆
     1. ├─testthat::expect_identical(...) at test-http.R:81:3
     2. │ └─testthat::quasi_label(enquo(expected), expected.label)
     3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
     4. └─rsconnect (local) signRequestPrivateKeyOpenSSL(private_key, url)
     5.   └─openssl::signature_create(charToRaw(canonicalRequest), key = private_key) at test-http.R:74:5
     6.     └─openssl:::hash_sign(md, sk)
    
    [ FAIL 1 | WARN 0 | SKIP 134 | PASS 675 ]
    Error:
    ! Test failures.
    Execution halted
Flavor: [r-devel-linux-x86_64-fedora-clang](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/rsconnect-00check.html)
```

```
• On Linux (3): 'test-locale.R:2:3', 'test-locale.R:9:3', 'test-utils.R:112:3'
    
    ══ Failed tests ════════════════════════════════════════════════════════════════
    ── Error ('test-http.R:74:5'): authHeaders() picks correct method based on supplied fields ──
    Error in `hash_sign(md, sk)`: OpenSSL error: 40D95840C97F0000:error:03000098:digital envelope routines:evp_pkey_ctx_set_md:invalid digest:crypto/evp/pmeth_lib.c:966:
    
    Backtrace:
        ▆
     1. ├─testthat::expect_identical(...) at test-http.R:81:3
     2. │ └─testthat::quasi_label(enquo(expected), expected.label)
     3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
     4. └─rsconnect (local) signRequestPrivateKeyOpenSSL(private_key, url)
     5.   └─openssl::signature_create(charToRaw(canonicalRequest), key = private_key) at test-http.R:74:5
     6.     └─openssl:::hash_sign(md, sk)
    
    [ FAIL 1 | WARN 0 | SKIP 134 | PASS 675 ]
    Error:
    ! Test failures.
    Execution halted
Flavor: [r-devel-linux-x86_64-fedora-gcc](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-gcc/rsconnect-00check.html)
```

### PR DESCRIPTION
**Pull request by aronatkins**
some installations have openssl configurations which prohibit SHA-1 signatures.

fixes #1255

### CODE REVIEW

File: tests/testthat/test-http.R [hunk 1]
```diff
@@ -6,6 +6,8 @@ test_that("non-libCurl methods are deprecated", {
 # headers -----------------------------------------------------------------
 
 test_that("authHeaders() picks correct method based on supplied fields", {
+  skip_on_cran() # CRAN may not have an openssl that permits SHA-11 signatures.
```
Comment (karawoo) [inline tests/testthat/test-http.R]:
```suggestion
  skip_on_cran() # CRAN may not have an openssl that permits SHA-1 signatures.
```
