### PR TITLE
fix: Allow browser authentication to Snowflake from the Deploy pane

### LINKED ISSUE #1289: Interactive Snowflake authentication doesn't work when deploying from RStudio
### Description

Now that we've fixed some of the Snowflake-related issues for RStudio, one major one remains: the Deploy pane doesn't permit "interactive" flows like those we use for `externalbrowser` auth:

Image

### Your environment

- rsconnect dev

### PR DESCRIPTION
**Pull request by atheriel**
The `snowflakeauth` package only permits external browser authentication from interactive contexts, which makes sense in most cases.

However, push-button deployments from the RStudio IDE actually run in a separate Deploy pane, not from the interactive console -- which isn't considered "interactive" by default.

So this commit tells `rlang` to temporarily treat this as an interactive context, which allows the browser flow to work.

This actually requires a change to the `snowflakeauth` package as well: https://github.com/posit-dev/snowflakeauth/commit/dbd4830f1db8cf4c73b59608d6289a60a280142f. We'll have to get another release of that package out to enable this fix to work properly.

Fixes #1289.

### CODE REVIEW

File: R/client-connect.R [hunk 1]
```diff
@@ -165,6 +165,15 @@ getSnowflakeAuthToken <- function(url, snowflakeConnectionName) {
   parsedURL <- parseHttpUrl(url)
   ingressURL <- parsedURL$host
 
+  # Detect when we're running in the Deploy pane of RStudio and enable
+  # "interactive" temporarily so that external browser authentication is
+  # permitted.
+  if (rstudioapi::isBackgroundJob()) {
+    prev <- getOption("rlang_interactive")
+    options("rlang_interactive" = TRUE)
```
Comment (aronatkins) [inline R/client-connect.R]: Could this use `rlang::local_options()`? https://rlang.r-lib.org/reference/local_options.html

File: R/client-connect.R [hunk 2]
```diff
@@ -165,6 +165,15 @@ getSnowflakeAuthToken <- function(url, snowflakeConnectionName) {
   parsedURL <- parseHttpUrl(url)
   ingressURL <- parsedURL$host
 
+  # Detect when we're running in the Deploy pane of RStudio and enable
+  # "interactive" temporarily so that external browser authentication is
+  # permitted.
+  if (rstudioapi::isBackgroundJob()) {
```
Comment (aronatkins) [inline R/client-connect.R:171]: There is a mix of calls to `base::interactive()` and `rlang::is_interactive()`. Should they all shift to `rlang::is_interactive()`? Alternatively, should we have our own internal `is_interactive()` implementation which consults `rstudioapi::isBackgroundJob()`?

**Review by aronatkins — APPROVED** [review]

File: R/client-connect.R (hunk 2 above)
Comment (atheriel) [reply R/client-connect.R:171]: I feel like this targeted fix is what I'm after for now. Changing how we think about `interactive()` everywhere might have other side effects.
