### PR TITLE
Use output from `getAuthedUser()` when creating a `connectApiUser()`

### LINKED ISSUE #402: connectApiUser generates partial configuration
The `rsconnect::connectApiUser` function doesn't appear to generate a usable account configuration.

```
server_url <- "https://connect.my-company.io/"
server_name <- "connect.my-company.io"
account <- "jeff.keller@my-company.com"
apiKey <- Sys.getenv("RSTUDIO_CONNECT_API_KEY")
rsconnect::addServer(url = server_url, name = server_name)
rsconnect::connectApiUser(account = account, server = server_name, apiKey = apiKey)
```
This generates the file
```
~/.config/R/rsconnect/accounts/connect.my-company.io/jeff.keller@my-company.com
```
with contents
```
username: jeff.keller@my-company.com
accountId: 0
apiKey: <REDACTED>
server: connect.my-company.io
```
Which doesn't work for publishing content to Connect. If I "reconnect" the account through the RStudio GUI, the contents of the `.dcf` file become:

```
username: jeff.keller@my-company.com
accountId: 3
token: <REDACTED>
server: connect.my-company.io
private_key:
           <REDACTED>

```

Which works fine for publishing. How can I use `rsconnect:connectApiUser` to publish content without authenticating via the browser?

**Software versions**
`rsconnect` v0.8.16
RStudio Connect v1.7.8-7
Build "1144ac9"

### PR DESCRIPTION
**Pull request by schloerke**
Fixes #402 

* I also removed some (what I think is) dead code, where the `userId` and `accountDetails` values that are being set are not used outside of the code chunk.

### CODE REVIEW

File: R/accounts.R [hunk 1]
```diff
@@ -73,21 +73,6 @@ connectApiUser <- function(account = NULL, server = NULL, apiKey = NULL, quiet =
...
-  # if account is specified and we already know about the account, get the User
-  # ID so we can prefill authentication fields
-  userId <- 0
-  userAccounts <- accounts(target$name)
-  if (!is.null(account) && !is.null(userAccounts)) {
-    if (account %in% userAccounts[,"name"]) {
-      accountDetails <- accountInfo(account, target$name)
-      userId <- accountDetails$accountId
-      if (!quiet) {
-        message("The account '",  account, "' is already registered; ",
```
Comment (jmcphers) [inline R/accounts.R]: I think we need to keep this message so that you know if you're overwriting an existing account.

File: R/accounts.R [hunk 2]
```diff
@@ -98,7 +83,7 @@ connectApiUser <- function(account = NULL, server = NULL, apiKey = NULL, quiet =
   # write the user info
   registerUserApiKey(serverName = target$name,
                     accountName = account,
-                    userId = userId,
```
Comment (jmcphers) [inline R/accounts.R]: I think the intent here was to pick up the userId from disk if it was present there, and to ask the server otherwise. It is probably okay to just use the value from the server all the time though!

File: R/accounts.R (hunk 1 above)
Comment (schloerke) [reply R/accounts.R]: 👍 I'll add back the two sections.

File: R/accounts.R (hunk 2 above)
Comment (schloerke) [reply R/accounts.R]: 👍

**Comment by schloerke** [comment]
Force push changes:
* Removed the `remove dead code` commit 
* Squashed the dev version and news information

**Comment by schloerke** [comment]
Working example: https://github.com/rstudio/shinycoreci-apps/runs/464989623?check_suite_focus=true#step:10:13
