### PR TITLE
paginate through connect application lists

### LINKED ISSUE #860: Updating an existing deployment using `appName` fails
Updating an existing deployment without an `rsconnect` subdir present fails when selecting the content to update using `appName`. (Updating using `appId` seems to work.)

The logs (attached) make it seem like maybe `rsconnect` is calling Connect's API expecting to get a single result, but is getting multiple results, and is thus passing a vector of URLs to `curl` instead of a single URL.

The presence of multiple seemingly-identical results might be a Connect bug, or it might be incorrect API usage. (Perhaps the endpoint is returning all matching bundles, rather than all matching content items.)

```
> rsconnect::deployDoc("index.Rmd", appName = "test-rmds")
ℹ Discovering document dependencies...
✔ Document dependencies discovered
── Preparing for deployment ────────────────────────────────────────────────────────────────────────────────────────
Found multiple accounts.
Which one do you want to use?
1: server: localhost / username: toph
2: server: rsc.radixu.com / username: toph
Selection: 1
Discovered a previously deployed app named "test-rmds", "test-rmds", "test-rmds", "test-rmds", "test-rmds", and
"test-rmds"
(View it at <http://localhost:3939/content/6441c48e-771b-4db6-ab58-fda27a036386/>,
<http://localhost:3939/content/6441c48e-771b-4db6-ab58-fda27a036386/>,
<http://localhost:3939/content/6441c48e-771b-4db6-ab58-fda27a036386/>,
<http://localhost:3939/content/6441c48e-771b-4db6-ab58-fda27a036386/>,
<http://localhost:3939/content/6441c48e-771b-4db6-ab58-fda27a036386/>, and
<http://localhost:3939/content/6441c48e-771b-4db6-ab58-fda27a036386/>)
What do you want to do?
1: Update the existing app.
2: Create a new app with automatically generated name ("test-rmds-1").
3: Abort this deployment and supply a custom `appName`.
Selection: 1
✔ Re-deploying "test-rmds", "test-rmds", "test-rmds", "test-rmds", "test-rmds", and "test-rmds" to "server: localhost / username: toph"
ℹ Looking up application with id 522, 522, 522, 522, 522, and 522...
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Argument 'url' must be string.
```

### PR DESCRIPTION
**Pull request by aronatkins**
fixes #860

### CODE REVIEW

File: R/client.R [hunk 1]
```diff
@@ -44,6 +46,46 @@ listRequest <- function(service, authInfo, path, query, listName, page = 100,
...
+# To paginate, use the query arguments cont=CONTINUATION&start=START&count=MAX
+listApplicationsRequest <- function(service, authInfo, path, query, listName, page = 100,
+                       max = NULL) {
+
+  # accumulate multiple pages of results
+  start <- 0
+  cont <- ""
+  results <- list()
+
+  while (TRUE) {
```
Comment (hadley) [inline R/client.R:59]:
```suggestion
  repeat {
```

File: R/client-connect.R [hunk 2]
```diff
@@ -45,7 +45,7 @@ connectClient <- function(service, authInfo) {
         c("account_id", names(filters)),
         c(accountId, unname(filters))
       ), collapse = "&")
-      listRequest(service, authInfo, path, query, "applications")
+      listApplicationsRequest(service, authInfo, path, query, "applications")
```
Comment (hadley) [inline R/client-connect.R:48]: Any concerns about this bug also occuring for other clients?

**Review by hadley — APPROVED** [review]

File: R/client-connect.R (hunk 2 above)
Comment (aronatkins) [reply R/client-connect.R:48]: No. The Connect internal applications API does pagination differently from other APIs.
