### PR TITLE
Strip trailing slashes in ensureConnectServer()

### LINKED ISSUE #603: API Key Workflow and Server Registration should have better diagnostics
Server registration right now is fairly naive and the happy path is pretty narrow. Even savvy users can get tripped up by this.

In particular, you _must_ have `/__api__` _with no trailing slash_ in order to have a functional server definition.

- To reproduce a 404 issue (missing `__api__` in server URL):
```
rsconnect::addServer("https://myserver.com", "training")
# Server 'training' added successfully: https://myserver.com
rsconnect::connectApiUser("cole", "training", "mykey")
# Account registered successfully: cole
rsconnect::deployApp("./test-123/", server = "training", account = "cole")
# Preparing to deploy application...Error: HTTP 404
# GET https://myserver.com/applications?filter=account_id:2&filter=name:test-123&count=100&offset=0
# 404 page not found
```
- To reproduce a different error (trailing slash)
```
rsconnect::addServer("https://myserver.com/__api__/", "training")
# Server 'training' added successfully: https://myserver.com/__api__/
rsconnect::deployApp("./test-123/", server = "training", account = "cole")
# Preparing to deploy application...Error in response[[listName]] : subscript out of bounds
```
- Success (no trailing slash)
```
rsconnect::addServer("https://myserver.com/__api__", "training")
# Server 'training' added successfully: https://myserver.com/__api__
rsconnect::deployApp("./test-123/", server = "training", account = "cole")
# Preparing to deploy application...DONE
# Uploading bundle for application: 56...DONE
# Deploying bundle: 59 for application: 56 ...
# ...
```

### PR DESCRIPTION
**Pull request by hadley**
Fixes #603

### CODE REVIEW

File: tests/testthat/test-servers.R [hunk 1]
```diff
@@ -10,3 +10,12 @@ test_that("servers() redacts the certificate", {
...
   expect_snapshot(servers())
 })
+
+test_that("normalizes connect urls", {
+  expected <- "https://myserver.com/__api__"
+
+  expect_equal(ensureConnectServerUrl("https://myserver.com"), expected)
+  expect_equal(ensureConnectServerUrl("https://myserver.com/"), expected)
+  expect_equal(ensureConnectServerUrl("https://myserver.com/__api__"), expected)
+  expect_equal(ensureConnectServerUrl("https://myserver.com/__api__/"), expected)
```
Comment (hadley) [inline tests/testthat/test-servers.R:20]: This last test failed previously

File: R/servers.R [hunk 2]
```diff
@@ -296,11 +296,12 @@ clientForAccount <- function(account) {
 }
 
 ensureConnectServerUrl <- function(url) {
+  # strip trailing /
+  url <- gsub("/$", "", url)
```
Comment (aronatkins) [inline R/servers.R:300]: This function needs to return a URL that can be concatenated with sub-paths like `/content`, which is why `/__api__` isn't given a trailing slash.

The bit that smooshes it all together:
https://github.com/rstudio/rsconnect/blob/5e0189d2e52c6708af942a600b115530c0094b1f/R/http.R#L276-L277

**Review by aronatkins — APPROVED** [review]
