### PR TITLE
fix renv profiles

### LINKED ISSUE #1300: Deploying with renv profiles uses wrong lockfile
### Description

When deploying a project that uses an renv profile, `deployApp()` fails with "Library and lockfile are out of sync" even though `renv::restore()` confirms the library is synchronized. The issue is that `bundleAppDir()` copies project files into a temp staging directory, and the renv/ directory is excluded from bundling (as expected). But when using an renv profile like 'dev', the profile-specific lockfile lives at renv/profiles/dev/renv.lock, so it gets excluded too. Only the root renv.lock (from the default profile) ends up in the bundle.

Later, `parseRenvDependencies()` reads this default-profile lockfile and compares versions against the library, which has packages from the active profile. The versions don't match, producing the error.

### Your environment

_No response_

### PR DESCRIPTION
**Pull request by karawoo**
fixes #1300 by ensuring that we copy the profile renv.lock file into the temp directory when creating the bundle

### CODE REVIEW

File: R/bundle.R [hunk 1]
```diff
@@ -45,6 +45,21 @@ bundleAppDir <- function(
...
+  # entire renv/ directory is ignored). Resolve the correct lockfile from the
+  # original appDir and copy it into the bundle so that
+  # parseRenvDependencies() compares against the right lockfile.
+  profileLockfile <- tryCatch(
+    resolveRenvLockFile(appDir),
+    error = function(e) NULL
+  )
+  if (!is.null(profileLockfile) && file.exists(profileLockfile)) {
+    bundleLockfile <- file.path(bundleDir, "renv.lock")
+    file.copy(profileLockfile, bundleLockfile, overwrite = TRUE)
```
Comment (aronatkins) [inline R/bundle.R:60]: Ah. This replaces the primary `renv.lock` with the named profile lock file.

Comment (karawoo) [reply R/bundle.R:60]: yes, just in the temp directory, not the project source
