### PR TITLE
fix: Disable httr2 for shinyapps.io bundle uploads

### LINKED ISSUE #1297: deployApp() fails with "bad checksum" when uploading bundle to shinyapps.io
### Description

 **Summary**                                                                                                                                                            
                                                                                                                                                                     
Deploying a Shiny app to shinyapps.io with deployApp() fails with a "bad checksum" HTTP 400 error during bundle upload. This happens consistently with the dev version of rsconnect installed from GitHub. 

```
GithubRepo: | rsconnect
-- | --
GithubUsername: | rstudio
GithubRef: | HEAD
GithubSHA1: | 591e6527751f08f6d75ab0109ef4ca1406341b5f
```

**Steps to reproduce**
1. remotes::install_github("rstudio/rsconnect")
2. rsconnect::deployApp(appDir = "/path/to/shiny/app")

Error

  Error in `POST()`:
  ! <https://api.shinyapps.io/v1/bundles/11663820> failed with HTTP status 400
  bad checksum




<details><summary>with options(rsconnect.httr2 = FALSE)  App deployment succeeds: </summary>

```
> options(rsconnect.httr2 = FALSE)   
> getOption("rsconnect.httr2")  
[1] FALSE
> rsconnect::deployApp(appDir = "/Users/cchaudhari/shinyapp/shinyapp", appName = "shinyapp-1")
── Preparing for deployment ───────────────────────────────────────────────────────────────────
✔ Re-deploying "shinyapp-1" using "server: shinyapps.io / username: chaitatest"
ℹ Looking up content with id "16818495"...
✔ Found content <https://chaitatest.shinyapps.io/shinyapp-1/>
ℹ Bundling 1 file: app.R
ℹ Capturing R dependencies
✔ Found 30 dependencies
✔ Created bundle of size: 20,241b
ℹ Uploading bundle...
✔ Uploaded bundle with id 11663834
── Deploying to server ────────────────────────────────────────────────────────────────────────
Waiting for task: 1659510191
  building: Building image: 14484050
  building: Fetching packages
  building: Installing packages
  building: Installing files
  building: Pushing image: 14484050
  deploying: Starting instances
  rollforward: Activating new instances
  success: Stopping old instances
── Deployment complete ────────────────────────────────────────────────────────────────────────
✔ Successfully deployed to <https://chaitatest.shinyapps.io/shinyapp-1/>
```

</details>


<details><summary> with > options(rsconnect.httr2 = TRUE) app deployment fails </summary>

```
> options(rsconnect.httr2 = TRUE)
> getOption("rsconnect.httr2")  
[1] TRUE
> rsconnect::deployApp(appDir = "/Users/cchaudhari/shinyapp/shinyapp", appName = "shinyapp-1")
── Preparing for deployment ───────────────────────────────────────────────────────────────────
✔ Re-deploying "shinyapp-1" using "server: shinyapps.io / username: chaitatest"
ℹ Looking up content with id "16818495"...
✔ Found content <https://chaitatest.shinyapps.io/shinyapp-1/>
ℹ Bundling 1 file: app.R
ℹ Capturing R dependencies
✔ Found 30 dependencies
✔ Created bundle of size: 20,243b
ℹ Uploading bundle...
Error in `POST()`:
! <https://api.shinyapps.io/v1/bundles/11663843> failed with HTTP status 400
bad checksum
Run `rlang::last_trace()` to see where the error occurred.
```




### Your environment

_No response_

### PR DESCRIPTION
**Pull request by ChaitaC**
## Update: 
The final approach changed during review. Instead of disabling httr2 for shinyapps.io, we disable httr2's automatic redirect  following (`followlocation = FALSE`) and handle redirects manually in `httpRequestWithBody`. This allows httr2 to remain enabled for all  servers including shinyapps.io.            

--------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------

## Summary

- Disables httr2 for the shinyapps.io bundle upload flow by setting `rsconnect.httr2 = FALSE` in `uploadShinyappsBundle()`
- The shinyapps.io API returns a 303 redirect during `updateBundleStatus`, and httr2 drops the request body on redirect while keeping the `X-Content-Checksum` header, causing a "bad checksum" HTTP 400 error
- The option is restored after the upload completes via `on.exit()`

Fixes #1297

### CODE REVIEW

**Comment by ChaitaC** [comment]
> I wonder if instead we could prevent httr2 from following redirects (`httr2::req_options(req, followlocation = FALSE)`). We already have code to handle redirects ourselves in `httpRequestWithBody`:
> 
> https://github.com/rstudio/rsconnect/blob/591e6527751f08f6d75ab0109ef4ca1406341b5f/R/http.R#L131-L146

Thanks, @karawoo, for taking a look!   I'm not super familiar with the httr2 internals to be confident making deeper changes to the redirect handling. I've updated the PR with a broader workaround that disables httr2 for all shinyapps.io API calls, and the integration tests pass locally.

A couple of things I found while testing:                                                                                                                                                                                           
  - isRedirect() checks for 301, 302, 307, 308, but not 303, which is what shinyapps.io returns.                                       
  - The issue isn't just updateBundleStatus — deployApplication also gets a 303 redirect and fails with 405. So the fix needs to cover all shinyapps.io POST endpoints.                                                                                                   
                                                                                                                                      
@nealrichardson I've added the workaround for shinyapps.io and have integration tests passing locally. When we're ready to run them in CI, we'll need someone with admin access to add the shinyapps.io credentials as repository secrets. Also, Kara's suggestion of using `followlocation = FALSE` could be a cleaner long-term fix — let me know if you'd like to go that route instead.

File: R/http.R [hunk 1]
```diff
@@ -155,7 +183,7 @@ httpRequestWithBody <- function(
 }
 
 isRedirect <- function(status) {
-  status %in% c(301, 302, 307, 308)
+  status %in% c(301, 302, 303, 307, 308)
```
Comment (nealrichardson) [inline R/http.R]: Are we sure we need this change? I don't recall touching this when adding httr2 support. Is it possible that the reason the shinyapps code works in the old http backend is that it's just not following the 303 at all?

Comment (karawoo) [reply R/http.R]: @nealrichardson you're right, the legacy backend was never following the 303 and httr2 can do the same. I was mistaken in my earlier comment about adding it. removing the 303 here will fix the `terminateApp()` call that is currently failing the integration test.

File: R/http.R [hunk 2]
```diff
@@ -35,6 +35,20 @@ httpRequest <- function(
...
+        service,
+        authInfo,
+        "GET",
+        service$path,
+        headers,
+        timeout,
+        certificate
+      )
+      httpResponse <- httr2_response_to_list(resp)
+    }
```
Comment (ChaitaC) [inline R/http.R:51]: Note: Since followlocation = FALSE is global, GET requests through httpRequest() also stopped following redirects, which broke unit tests (test-http:206, test-ide:48-49). Added a redirect loop in httpRequest() to fix this.

File: R/http.R (hunk 1 above)
Comment (ChaitaC) [reply R/http.R]: Removed the 303 — all unit tests and integration tests (deploy + terminate) pass locally.

File: tests/shinyapps-integration/setup.R [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+shinyapps_name <- Sys.getenv("SHINYAPPS_NAME")
+shinyapps_token <- Sys.getenv("SHINYAPPS_TOKEN")
+shinyapps_secret <- Sys.getenv("SHINYAPPS_SECRET")
+
+if (shinyapps_name == "" || shinyapps_token == "" || shinyapps_secret == "") {
+  skip(
+    "SHINYAPPS_NAME, SHINYAPPS_TOKEN, and SHINYAPPS_SECRET must be set to run shinyapps.io integration tests."
+  )
+}
+
```
Comment (karawoo) [inline tests/shinyapps-integration/setup.R]: I don't know for sure, but it seems like the failing tests have to do with how shinyapps.io resolves repositories from the manifest. I'd try adding something like that to see if that helps

```suggestion
original_repos <- getOption("repos")
if ("RSPM" %in% names(original_repos) && !"CRAN" %in% names(original_repos)) {
  cran_repos <- original_repos
  names(cran_repos)[names(cran_repos) == "RSPM"] <- "CRAN"
  options(repos = cran_repos)
  withr::defer(options(repos = original_repos), teardown_env())
}
```

File: R/http.R (hunk 1 above)
Comment (ChaitaC) [reply R/http.R]: The current integration failures appear to be related to shinyapps.io infrastructure issues, where the build server is unable to fetch packages. I will make necessary changes to resolve this issue.

File: tests/shinyapps-integration/setup.R (hunk 3 above)
Comment (ChaitaC) [reply tests/shinyapps-integration/setup.R]: I reverted my pre-generated manifest approach in this case and commited yours. Thanks for all the help getting this PR in mergable state. It's ready for re-review

File: R/http.R [hunk 4]
```diff
@@ -115,6 +129,20 @@ httpRequestWithBody <- function(
...
     )
     httpResponse <- httr2_response_to_list(resp)
+
+    while (isRedirect(httpResponse$status)) {
+      service <- redirectService(service, httpResponse$location)
+      authed_headers <- c(headers, authHeaders(authInfo, "GET", service$path))
+      resp <- httr2Request(
+        service,
+        authInfo,
+        "GET",
```
Comment (karawoo) [inline R/http.R:139]: this matches line 169 where we intentionally pass `"GET"` even though the original request was a different method 👍

File: tests/shinyapps-integration/setup.R [hunk 5]
```diff
@@ -0,0 +1,47 @@
+library(testthat)
+library(rsconnect)
+
+# Skip if shinyapps.io credentials are not available
+shinyapps_name <- Sys.getenv("SHINYAPPS_NAME")
+shinyapps_token <- Sys.getenv("SHINYAPPS_TOKEN")
+shinyapps_secret <- Sys.getenv("SHINYAPPS_SECRET")
+
+if (shinyapps_name == "" || shinyapps_token == "" || shinyapps_secret == "") {
+  skip(
```
Comment (nealrichardson) [inline tests/shinyapps-integration/setup.R]: Since this is in a separate test suite that won't get run normally, we could fail harder if the necessary secrets aren't found, we don't have to worry about skipping on CRAN for example.

```suggestion
  stop(
```
