### PR TITLE
JSON error is a list of character vectors

### LINKED ISSUE #997: configureApp fails with  error in rlang::abort()
I am trying to set size with configureApp and it fails with rlang::abort()

```
> rsconnect::configureApp("asc_seurat", size="xlarge")
Error in `rlang::abort()`:
! `message` must be a character vector, not a list.
Run `rlang::last_trace()` to see where the error occurred
> rlang::last_trace(drop = FALSE)
<error/rlang_error>
Error in `rlang::abort()`:
! `message` must be a character vector, not a list.
---
Backtrace:
     ▆
  1. └─rsconnect::configureApp("asc_seurat", size = "xlarge")
  2.   └─client$setApplicationProperty(application$id, propertyName, propertyValue)
  3.     └─rsconnect:::PUT_JSON(service, authInfo, path, v, query)
  4.       └─rsconnect:::PUT(...)
  5.         └─rsconnect:::httpRequestWithBody(...)
  6.           └─rsconnect:::handleResponse(httpResponse, error_call = error_call)
  7.             └─rsconnect (local) reportError(json$error)
  8.               └─cli::cli_abort(...)
  9.                 └─rlang::abort(message = message)
 10.                   └─rlang:::validate_signal_args(...)
 11.                     └─rlang:::check_character(message, call = env)
 12.                       └─rlang:::stop_input_type(...)
 13.                         └─rlang::abort(message, ..., call = call, arg = arg)
```

```
> session_info()
─ Session info ──────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.1 (2023-06-16)
 os       macOS Ventura 13.5.2
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
  rstudio  2023.06.1+524 Mountain Hydrangea (desktop)
 pandoc   3.1.7 @ /opt/homebrew/bin/pandoc
```

Please let me know if you have seen this error and if have a solution for this. If it is already posted and addressed, please share the link.

### PR DESCRIPTION
**Pull request by hadley**
Fixes #997

### CODE REVIEW

File: R/http.R [hunk 1]
```diff
@@ -150,7 +150,7 @@ handleResponse <- function(response, error_call = caller_env()) {
     if (response$status %in% 200:399) {
       out <- json
     } else if (!is.null(json$error)) {
-      reportError(json$error)
+      reportError(unlist(json$error))
```
Comment (aronatkins) [inline R/http.R:153]: From Connect, the `json$error` field is a simple string. 

```json
{
  "code": 123,
  "error": "something happened"
}
```

**Review by aronatkins — APPROVED** [review]

File: R/http.R (hunk 1 above)
Comment (aronatkins) [reply R/http.R:153]: I have also confirmed that shinyapps.io errors have a simple string for `json$string`.
